name: Cypress Tests

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          config-file: cypress.config.ts
          command:  npx cypress run --spec cypress/features/Products_Supported.feature --browser chrome